# Generated by Django 4.0.4 on 2022-05-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_from_time', models.TimeField(max_length=20)),
                ('doctor_to_time', models.TimeField(max_length=20)),
                ('doctor_date', models.DateField(max_length=10)),
                ('timetable_doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_doctor_id', to='website.doctor_profile')),
            ],
        ),
    ]
