# Generated by Django 4.0.4 on 2022-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_doctor_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_booking',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
